/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyJNITest */

#ifndef _Included_MyJNITest
#define _Included_MyJNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyJNITest
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_MyJNITest_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
